apiVersion: v1
kind: ConfigMap
metadata:
  namespace: fitness-challenge
  name: persistence-fitness-challenge-config
data:
  spring.datasource.url: jdbc:mysql://persistence-mysql-svc.fitness-challenge.svc.cluster.local:3306/fitness_challenge
  spring.datasource.username: fitness-challenge
  spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
  MYSQL_USER: fitness-challenge
  MYSQL_DATABASE: fitness_challenge